server:
  port: 8090

spring:
  profiles:
    include: secret

  #spring.jpa.hibernate.ddl-auto: ??? ??? ??? ??? ???? ???? ???? ?????.
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect

    #spring.jpa.properties.hibernate.format_sql: Hibernate ?? ? SQL ??? ??, ???? ?? ??? ?? ?? ???
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true         # SQL에 색상 부여 (터미널에서 가독성 향상)
        use_sql_comments: true      # 쿼리에 주석 추가

    show-sql: true

  # Message settings
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

springdoc:
  swagger-ui:
    query-config-enabled: false

jwt:
  secret: toyproject-secret-key-1234567890-abcdefg
  token-validity: 3600000 # 1시간

logbook:
  filter:
    enabled: false

logging:
  level:
    root: info
    org.zalando.logbook: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG