server:
  port: 8090

spring:
  profiles:
    include: secret

  #spring.jpa.hibernate.ddl-auto: ??? ??? ??? ??? ???? ???? ???? ?????.
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    #spring.jpa.properties.hibernate.format_sql: Hibernate ?? ? SQL ??? ??, ???? ?? ??? ?? ?? ???
    properties:
      hibernate:
        format_sql: true

    show-sql: true

  # Message settings
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

springdoc:
  swagger-ui:
    query-config-enabled: false

jwt:
  secret: toyproject-secret-key-1234567890-abcdefg
  token-validity: 3600000 # 1시간