spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/toyproject
    username: root
    password: 123

  #spring.jpa.hibernate.ddl-auto: ??? ??? ??? ??? ???? ???? ???? ?????.
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    #spring.jpa.properties.hibernate.format_sql: Hibernate ?? ? SQL ??? ??, ???? ?? ??? ?? ?? ???
    properties:
      hibernate:
        format_sql: true

    show-sql: true

#      hibernate:
#        jdbc:
#          time_zone: UTC
#        format_sql: true
#        highlight_sql: true
#        default_batch_fetch_size: 100
#        generate_statistics: false